# Generated by Django 4.2.11 on 2024-03-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1023)),
                ('channel', models.ManyToManyField(related_name='cost_structure', to='canvas.channel')),
                ('customer_relationship', models.ManyToManyField(related_name='cost_structure', to='canvas.customerrelationship')),
                ('customer_segment', models.ManyToManyField(related_name='cost_structure', to='canvas.customersegment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_structure', to='canvas.project')),
                ('value_propositions', models.ManyToManyField(related_name='cost_structure', to='canvas.valueproposition')),
            ],
        ),
    ]
