# Generated by Django 4.2.11 on 2024-03-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_coststructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coststructure',
            name='channel',
            field=models.ManyToManyField(blank=True, related_name='cost_structure', to='canvas.channel'),
        ),
        migrations.AlterField(
            model_name='coststructure',
            name='customer_relationship',
            field=models.ManyToManyField(blank=True, related_name='cost_structure', to='canvas.customerrelationship'),
        ),
        migrations.AlterField(
            model_name='coststructure',
            name='customer_segment',
            field=models.ManyToManyField(blank=True, related_name='cost_structure', to='canvas.customersegment'),
        ),
        migrations.AlterField(
            model_name='coststructure',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='coststructure',
            name='value_propositions',
            field=models.ManyToManyField(blank=True, related_name='cost_structure', to='canvas.valueproposition'),
        ),
    ]
