# Generated by Django 4.2.11 on 2024-04-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_alter_coststructure_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrelationship',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='keyactivities',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='keypartnership',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='keyresources',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
    ]
