# Generated by Django 4.2.11 on 2024-05-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_alter_customerrelationship_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='customer_segments',
            new_name='customer_segment',
        ),
    ]
